# Found at: https://loiane.com/2024/03/github-actions-for-angular-projects-cicd-pipeline-for-testing-building-and-ng-update/

name: Angular Build

# {1}
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      VERSION: 1.0.0

    steps:
      # {2}
      - name: Checkout the source code
        uses: actions/checkout@v4

      # {3}
      - name: Setup Node.js 20.15.0
        uses: actions/setup-node@v3
        with:
          node-version: 20.15.0

      # {4}
      - name: Build & Deploy
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        working-directory: ./flight-booker
        run: |
          npm install
          npm run ng --build --base-href="/$VERSION/"
          git clone --branch gh-pages https://github.com/APettit98/SWE632-Project.git gh-pages
          rm -rf gh-pages/$VERSION
          cp -r  ./flight-booker/dist/flight-booker gh-pages/$VERSION
          cd gh-pages
          git add .
          git commit -m "Deploy verion $VERSION to GitHubPages"
          git push
